### ISSUE TITLE
no matching manifest for linux/arm/v6 or /v7 in the manifest list entries (Raspberry Pi zero 2 W and Pi B)

### ISSUE THREAD

**Issue by str0om** [antonijn/mqtt4dsmr#2]
When I pull the image with docker-compose it gives:  "no matching manifest for linux/arm/v6  (or v7) in the manifest list entries".
I tried on Raspberry Pi zero 2 W and Pi B models.
Does it mean it will not work with these raspberry Pi models? 
If so, maybe specify the hardware requirements in the readme.

**Comment by antonijn** [comment]
These are some old models! These aren't in the automated builds yet, I'll add them and let you know. I don't have those models, so please do let me know if it works.

**Comment by str0om** [comment]
just trying now (18:02 CET), same message for the piB: no matching manifest ...../v6  in the manifest list entries

(piB is old indeed, but the pi zero 2 W is quite recent, using piB to read P1 smartmeter until now with Domoticz, but would like to try HA).

**Comment by antonijn** [comment]
Yes, sorry! I'll let you know when I get the build working. It's not as trivial as I initially thought, but hopefully I'll have something by tomorrow.

**Comment by antonijn** [comment]
An armv7 version is now available for tag v0.9.4. Unfortunately, for armv6 I'm running into the following bug: https://github.com/PyO3/pyo3/issues/3614

It's fixed upstream (https://github.com/PyO3/pyo3/pull/3619) but I suppose it will take a while before it gets into the cryptography package. Until then, an armv6 build is unfortunately off the table... I'll make sure to add it to the readme.

I do wonder why your Pi Zero 2 W reported problems initially, since its hardware definitely supports arm64, for which builds are available (I'm using them myself). Have you installed a 32 bit OS on it?

**Comment by str0om** [comment]
Thank you! Yes, running 32bit on the pi zero, I was able to get the docker
image running this morning.
Now I need to find out how to see the output in home assistent.


Op zo 11 feb 2024 om 01:21 schreef antonijn ***@***.***>:
